name: NugetPush
description: Push to nuget.
inputs:
  projects:
    required: true
    type: string
    description: json array of csproj paths relative to sln
  version:
    required: false
    type: string
  NUGET_SOURCE:
    required: true
    type: string
  NUGET_KEY:
    required: true
    type: string
  NUGET_SYM_SOURCE:
    required: true
    type: string

runs:
  using: "composite"
  steps:
  - name: pack
    run: |
      if [[ "${{ inputs.version }}" == "" ]]; then version="${{ env.GitBuildVersionSimple }}"; echo "unset version set:$version"; else version="${{ inputs.version }}";echo version set; fi;
      ${{ github.action_path }}/pack_and_push.sh "${{ inputs.projects }}" "$version" "${{ inputs.NUGET_KEY }}" ${{ inputs.NUGET_SOURCE }} ${{ inputs.NUGET_SYM_SOURCE }}
    shell: bash    
